### ISSUE TITLE
Incompatibility with Blood Magic

### ISSUE THREAD

**Issue by AfterRebelion** [Vazkii/Unmending#3]
When Blood Magic is installed, Unmending functionality breaks, and any item that had mending enchantment can be repaired.

This issue is only open here to make the it visible to anyone that had this happen to them, as I don't think this should be fixed in Unmending, but in Blood Magic

Detailed issue is located here:
https://github.com/WayofTime/BloodMagic/issues/1566

**Comment by Phillip-Harner** [comment]
Vazkii, would the following fix be acceptable to you? (assuming I don't code it too poorly)

Add an additional onExperiencePickup event handler with the highest priority. This event handler would remove the mending enchantment from every item and keep track of what level of mending each item had.

Add a few lines to the current onExperiencePickup handler that would re-apply those enchantments.

**Comment by AfterRebelion** [comment]
This was fixed by Blood Magic.
